/**
 * sync-icon-colors — generates icons.css and IconColor type from comete-design-tokens.
 *
 * Reads the compiled CSS from @aexae/comete-design-tokens, extracts all `--icon-*`
 * custom properties, and generates:
 *   - src/styles/icons.css   (CSS classes mapping color prop → token)
 *   - Patches src/types.ts   (IconColor union type)
 *
 * Run: pnpm sync-colors
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const TOKENS_CSS_PATH = resolve(
  import.meta.dirname,
  "../../comete-design-tokens/build/css/comete-tokens.css",
);
const ICONS_CSS_PATH = resolve(import.meta.dirname, "../src/styles/icons.css");
const TYPES_PATH = resolve(import.meta.dirname, "../src/types.ts");

// ---------------------------------------------------------------------------
// 1. Parse token names from CSS

const css = readFileSync(TOKENS_CSS_PATH, "utf-8");

// Match all `--icon-*:` declarations (deduplicate via Set)
const tokenRegex = /--icon-([\w-]+)\s*:/g;
const rawNames = new Set<string>();
for (const m of css.matchAll(tokenRegex)) {
  rawNames.add(m[1]);
}

// Convert kebab-case token suffix to camelCase prop name
// e.g. "accent-purple" → "accentPurple"
// Exception: "on-warning" stays "on-warning" (established API convention)
const KEEP_KEBAB = new Set(["on-warning"]);

function toPropName(s: string): string {
  if (KEEP_KEBAB.has(s)) return s;
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

// Build sorted list of { propName, tokenSuffix }
const colors = [...rawNames]
  .map((suffix) => ({ prop: toPropName(suffix), suffix }))
  .sort((a, b) => a.prop.localeCompare(b.prop));

console.log(`Found ${colors.length} icon color tokens:`);
for (const c of colors) {
  console.log(`  ${c.prop} → --icon-${c.suffix}`);
}

// ---------------------------------------------------------------------------
// 2. Generate icons.css

const cssLines = [
  "/* Auto-generated by scripts/sync-icon-colors.ts — do not edit manually */",
  "/* Maps icon color props to Comète design token CSS custom properties */",
  "",
  ...colors.map(
    (c) => `.comete-icon--${c.prop} {\n  color: var(--icon-${c.suffix});\n}`,
  ),
  "",
];

writeFileSync(ICONS_CSS_PATH, cssLines.join("\n"));
console.log(`\n✔ Written ${ICONS_CSS_PATH}`);

// ---------------------------------------------------------------------------
// 3. Patch IconColor in types.ts

const types = readFileSync(TYPES_PATH, "utf-8");

const unionMembers = colors.map((c) => `  | "${c.prop}"`).join("\n");
const newType = `export type IconColor =\n${unionMembers};`;

const patched = types.replace(/export type IconColor =[\s\S]*?;/, newType);

if (patched === types) {
  console.error("⚠ Could not find IconColor type in types.ts — skipping patch");
} else {
  writeFileSync(TYPES_PATH, patched);
  console.log(`✔ Patched IconColor in ${TYPES_PATH}`);
}
